---
- name: Install Filebeat
  become: true
  apt:
    deb: "/tmp/filebeat-{{ filebeat_version }}-amd64.deb"
    state: present
  notify: restart Elasticsearch
- name: Set filebeat systemwork
  become: true
  command:
    cmd: filebeat modules enable system
    chdir: /usr/share/filebeat/bin
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is already enable!'
- name: Load Kibana dashboard
  become: true
  command:
    cmd: filebeat setup
    chdir: /usr/share/filebeat/bin
  register: filebeat_setup
  changed_when: false
  until: filebeat_setup is succeeded
